question_data = [
    [{"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "English new wave musician Gary Numan founded the video game development company Facepunch Studios in March 2009.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "easy",
      "question": "Eurobeat is primarily an Italian genre of music.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Animals", "type": "boolean", "difficulty": "easy",
      "question": "In 2016, the IUCN reclassified the status of Giant Pandas from endangered to vulnerable.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
      "difficulty": "easy",
      "question": "Gosho Aoyama Made This Series: (Detective Conan \/ Case Closed!)",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "easy",
      "question": "&quot;HTML&quot; stands for Hypertext Markup Language.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "The names of Tom Nook&#039;s cousins in the Animal Crossing franchise are named &quot;Timmy&quot; and &quot;Jimmy&quot;.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Mythology", "type": "boolean", "difficulty": "easy",
      "question": "According to Greek Mythology, Atlas was an Olympian God.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "In Pok&eacute;mon, Bulbasaur is the only starter pokemon that is a Grass\/Poison type.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Animals", "type": "boolean", "difficulty": "easy",
      "question": "Cats have whiskers under their legs.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "Valve&#039;s &quot;Portal&quot; and &quot;Half-Life&quot; franchises exist within the same in-game universe.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Japanese Anime & Manga", "type": "boolean",
      "difficulty": "easy", "question": "Kiznaiver is an adaptation of a manga.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Television", "type": "boolean", "difficulty": "easy",
      "question": "Klingons express emotion in art through opera and poetry.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Art", "type": "boolean", "difficulty": "easy",
      "question": "Leonardo da Vinci was not the creator of the Mona Lisa.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "In Resident Evil 4, the Chicago Typewriter has infinite ammo.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "easy",
      "question": "The shotgun appears in every numbered Resident Evil game.",
      "correct_answer": "True", "incorrect_answers": ["False"]}],
    [{"category": "Celebrities", "type": "boolean", "difficulty": "medium",
      "question": "Michael Jackson had a pet python named &lsquo;Crusher&rsquo;.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Music", "type": "boolean", "difficulty": "medium",
      "question": "The cover of The Beatles album &quot;Abbey Road&quot; featured a Volkswagen Beetle in the background.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
      "question": "The planet Mars has two moons orbiting it.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Animals", "type": "boolean", "difficulty": "medium",
      "question": "&quot;Kamea,&quot; the Gilbertese Islander word for dog, is derived from the English phrase &quot;Come here!&quot;",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "medium",
      "question": "A defibrillator is used to start up a heartbeat once a heart has stopped beating.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Vehicles", "type": "boolean", "difficulty": "medium",
      "question": "The Chevrolet Corvette has always been made exclusively with V8 engines only.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
      "question": "In &quot;Team Fortress 2&quot;, the &quot;Bill&#039;s Hat&quot; is a reference to the game &quot;Dota 2&quot;.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Science: Computers", "type": "boolean", "difficulty": "medium",
      "question": "The last Windows operating system to be based on the Windows 9x kernel was Windows 98.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Television", "type": "boolean", "difficulty": "medium",
      "question": "Like his character in &quot;Parks and Recreation&quot;, Aziz Ansari was born in South Carolina.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
      "question": "The ADAM collecters in the Bioshock series are known as Little Sisters.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
      "question": "In &quot;League of Legends&quot;, there exists four different types of Dragon.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Animals", "type": "boolean", "difficulty": "medium",
      "question": "Finnish Lapphund dogs were used for herding reindeer.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "medium",
      "question": "Haggis is traditionally ate on Burns Night.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "medium",
      "question": "In career mode of &quot;Need for Speed: Underground 2&quot;, the first car the player can drive is the BMW M3 GTR.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Cartoon & Animations", "type": "boolean",
      "difficulty": "medium",
      "question": "Snagglepuss was part of the Yogi Yahooies in the 1977 show Scooby&#039;s All-Star Laff-a-Lympics.",
      "correct_answer": "False", "incorrect_answers": ["True"]}],
    [{"category": "Vehicles", "type": "boolean", "difficulty": "hard",
      "question": "In 1993 Swedish car manufacturer Saab experimented with replacing the steering wheel with a joystick in a Saab 9000.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "hard",
      "question": "It was once believed that injecting shark cartilage into people would prevent them from contracting cancer.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
      "question": "&quot;Number 16 Bus Shelter&quot; was a child&#039;s name that was approved by the New Zealand government.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
      "question": "If you could fold a piece of paper in half 50 times, its&#039; thickness will be 3\/4th the distance from the Earth to the Sun.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Entertainment: Video Games", "type": "boolean", "difficulty": "hard",
      "question": "In Undertale, having a &quot;Fun Value&quot; set to 56-57 will play the &quot;Wrong Number Song Call&quot;.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Geography", "type": "boolean", "difficulty": "hard",
      "question": "Switzerland has four national languages, English being one of them.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "History", "type": "boolean", "difficulty": "hard",
      "question": "The USS Missouri (BB-63) last served in the Korean War.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "Entertainment: Television", "type": "boolean", "difficulty": "hard",
      "question": "The Klingon home planet is Qo&#039;noS.", "correct_answer": "True",
      "incorrect_answers": ["False"]},
     {"category": "Science & Nature", "type": "boolean", "difficulty": "hard",
      "question": "The value of one Calorie is different than the value of one calorie.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "History", "type": "boolean", "difficulty": "hard",
      "question": "During the Winter War, the amount of Soviet Union soliders that died or went missing was five times more than Finland&#039;s.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
      "question": "Stagecoach owned &quot;South West Trains&quot; before losing the rights to FirstGroup and MTR in March of 2017.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Science: Mathematics", "type": "boolean", "difficulty": "hard",
      "question": "L&#039;H&ocirc;pital was the mathematician who created the homonymous rule that uses derivatives to evaluate limits with indeterminations.",
      "correct_answer": "False", "incorrect_answers": ["True"]},
     {"category": "General Knowledge", "type": "boolean", "difficulty": "hard",
      "question": "Spoon theory is a theory, utilizing &quot;Spoons&quot; as a metaphor for energy they can use in a day.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "History", "type": "boolean", "difficulty": "hard",
      "question": "The man that shot Alexander Hamilton was named Aaron Burr.",
      "correct_answer": "True", "incorrect_answers": ["False"]},
     {"category": "Geography", "type": "boolean", "difficulty": "hard",
      "question": "Only one country in the world starts with the letter Q.",
      "correct_answer": "True", "incorrect_answers": ["False"]}]
]

# # question_data = [
# #     {"text": "A slug's blood is green.", "answer": "True"},
# #     {"text": "The loudest animal is the African Elephant.", "answer": "False"},
# #     {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
# #     {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
# #     {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, "
# #              "you are free to take it home to eat.", "answer": "True"},
# #     {"text": "In London, UK, if you happen to die in the House of Parliament, "
# #              "you are entitled to a state funeral.", "answer": "False"},
# #     {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
# #     {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
# #     {"text": "Google was originally called 'Backrub'.", "answer": "True"},
# #     {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
# #     {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
# #     {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"}
# # ]
